name: publish nuget package

on:
  push:
    branches:
      - master
      - development

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.x'

    - name: restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build -c Release

    - name: set version and pack
      id: pack
      run: |
        BASE_VERSION="1.0.0"

        if [[ "${GITHUB_REF}" == "refs/heads/master" ]]; then
          VERSION="$BASE_VERSION"
        elif [[ "${GITHUB_REF}" == "refs/heads/development" ]]; then
          VERSION="${BASE_VERSION}-beta.${GITHUB_RUN_NUMBER}"
        else
          echo "current branch is not configured for publication. aborting..."
          exit 1
        fi

        echo "use version: $VERSION"
        dotnet pack -c Release -p:PackageVersion=$VERSION -o ./output --no-build

        echo "package_version=$VERSION" >> $GITHUB_OUTPUT

    - name: push package to nuget
      run: dotnet nuget push ./output/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate
